spring.application.name=stock-service
server.port=8082

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/stock_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# KIS API
kis.app-key=????APP_KEY
kis.app-secret=????APP_SECRET
kis.base-url=https://openapivts.koreainvestment.com:29443