spring:
  application:
    name: gateway-service
  data:
    redis:
      host: clustercfg.invest-redis.l9metn.apn2.cache.amazonaws.com
      port: 6379
  cloud:
    discovery:
      enabled: false
    gateway:
      httpclient:
        websocket:
          max-frame-payload-length: 65536
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
        - id: balance-service
          uri: http://balance-service:8083
          predicates:
            - Path=/api/balance/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
        - id: trade-service
          uri: http://trade-service:8084
          predicates:
            - Path=/api/trade/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
        - id: trade-service-ws
          uri: http://trade-service:8084
          predicates:
            - Path=/ws/**
        - id: stock-service
          uri: http://stock-service:8082
          predicates:
            - Path=/stocks/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
        - id: ai-service
          uri: http://ai-service:8085
          predicates:
            - Path=/api/ai/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
jwt:
  secret: ${JWT_SECRET}
server:
  port: 8080
