spring:
  application:
    name: gateway-service
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: user-service
          uri: http://10.0.3.195:8081
          predicates:
            - Path=/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10   # 초당 10개 허용
                redis-rate-limiter.burstCapacity: 20   # 최대 순간 20개
                redis-rate-limiter.requestedTokens: 1
        - id: balance-service
          uri: http://10.0.3.245:8083
          predicates:
            - Path=/api/balance/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
        - id: trade-service
          uri: http://10.0.3.103:8084
          predicates:
            - Path=/api/trade/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

jwt:
  secret: 12345678901234567890123456789012

server:
  port: 8080